#!/bin/bash

# Disconnect any currently connected bluetooth device before suspending
# Works around: LP bug #1075478
#
# Copyright: Copyright (c) 2013 Jamin Collins
# License:   BSD
#

case "${1}" in
    suspend)
        MACS=$(/usr/bin/hcitool con | /usr/bin/awk '/ACL/ {print $3}')
        # account for possibility of nothing being connected
        for MAC in ${MACS}; do
            /usr/bin/hcitool dc ${MAC}
        done
        ;;
    resume)
        # nothing
        ;;
esac
